//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ListViewWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ListView), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("UpdateView", UpdateView);
		L.RegFunction("GetChildern", GetChildern);
		L.RegFunction("GetChildViews", GetChildViews);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ListView obj = (ListView)ToLua.CheckObject<ListView>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateView(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChildern(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ListView obj = (ListView)ToLua.CheckObject<ListView>(L, 1);
			System.Collections.Generic.List<UnityEngine.GameObject> o = obj.GetChildern();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChildViews(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ListView obj = (ListView)ToLua.CheckObject<ListView>(L, 1);
			System.Collections.Generic.List<UIView> o = obj.GetChildViews();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

