//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MgrBase_ViewMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MgrBase<ViewMgr>), typeof(SingleBase<ViewMgr>), "MgrBase_ViewMgr");
		L.RegFunction("Begin", Begin);
		L.RegFunction("End", End);
		L.RegFunction("Init", Init);
		L.RegFunction("Shutdown", Shutdown);
		L.RegFunction("New", _CreateMgrBase_ViewMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMgrBase_ViewMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MgrBase<ViewMgr> obj = new MgrBase<ViewMgr>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MgrBase<ViewMgr>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Begin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MgrBase<ViewMgr> obj = (MgrBase<ViewMgr>)ToLua.CheckObject<MgrBase<ViewMgr>>(L, 1);
			obj.Begin();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int End(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MgrBase<ViewMgr> obj = (MgrBase<ViewMgr>)ToLua.CheckObject<MgrBase<ViewMgr>>(L, 1);
			obj.End();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MgrBase<ViewMgr> obj = (MgrBase<ViewMgr>)ToLua.CheckObject<MgrBase<ViewMgr>>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Shutdown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MgrBase<ViewMgr> obj = (MgrBase<ViewMgr>)ToLua.CheckObject<MgrBase<ViewMgr>>(L, 1);
			obj.Shutdown();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

