//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingleBase_ViewMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingleBase<ViewMgr>), typeof(System.Object), "SingleBase_ViewMgr");
		L.RegFunction("New", _CreateSingleBase_ViewMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Inst", get_Inst, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingleBase_ViewMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SingleBase<ViewMgr> obj = new SingleBase<ViewMgr>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SingleBase<ViewMgr>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Inst(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, SingleBase<ViewMgr>.Inst);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

