//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIUtil), typeof(System.Object));
		L.RegFunction("GetListView", GetListView);
		L.RegFunction("New", _CreateUIUtil);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUIUtil(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UIUtil obj = new UIUtil();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UIUtil.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetListView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIView arg0 = (UIView)ToLua.CheckObject<UIView>(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			ListView o = UIUtil.GetListView(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

