//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ViewMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ViewMgr), typeof(MgrBase<ViewMgr>));
		L.RegFunction("LoadView", LoadView);
		L.RegFunction("New", _CreateViewMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateViewMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ViewMgr obj = new ViewMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ViewMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ViewMgr obj = (ViewMgr)ToLua.CheckObject<ViewMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.LoadView(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

